### ISSUE TITLE
help with downloading

### ISSUE THREAD

**Issue by thaynos** [anime-dl/anime-downloader#684] opened 2021-05-24 16:24 UTC
im using a guest pc with no admin privileges
![image](https://user-images.githubusercontent.com/83282129/119377189-e4549c80-bccd-11eb-88f3-e92411e6f07f.png)
this happens when i try to open this file using anaconda prompt
im veery new to github scripts and im confused on what to do
ive heard something about path variable but it needs admin privileges 
is there any way to do without admin privileges

**Comment by ArjixWasTaken** [comment] 2021-05-24 16:57
ah yes, *the problem is clearly bc of admin privileges*
![image](https://user-images.githubusercontent.com/53124886/119381982-1d8b0d80-bcca-11eb-97e2-1888f8e70aa0.png)


There is no way you forgot an argument, for example ``install``, pffft, who runs ``python setup.py install``?
all my homies run ``python setup.py``.

**Comment by thaynos** [comment] 2021-05-24 18:57
i cant make head or tail of what u said lmfao
srsly tho can u help? in a simplified way?

**Comment by thaynos** [comment] 2021-05-24 19:00
nvm looking at it now i see that the command is install and i forgot install
in my defense other anime download scripts dint need the install command

**Comment by ArjixWasTaken** [comment] 2021-05-24 21:40
ay

**Comment by thaynos** [comment] 2021-05-25 05:21
how to launch the script now?

**Comment by thaynos** [comment] 2021-05-25 05:26
also is there any way to launch only the script in its own windows as if the script fails i have to type setup.py and the commands all over again

**Comment by thaynos** [comment] 2021-05-25 05:40
looking through the docs i noticed a gui command i downloaded the dependencies but how to actually run it?

**Comment by thaynos** [comment] 2021-05-25 05:58
also animepahe doesnt seem to be working even though its mentioned it works in the documentation
also how to do a re-search as sometimes all the results dont show
the one im searching for is nanatsu no taizai fundo no shinpan
![image](https://user-images.githubusercontent.com/83282129/119445401-d0488380-bd3d-11eb-8896-13f001631279.png)

**Comment by thaynos** [comment] 2021-05-25 06:13
im getting this issue now D:
![image](https://user-images.githubusercontent.com/83282129/119448018-d0e31900-bd41-11eb-8d90-d8b59846a60e.png)

**Comment by ArjixWasTaken** [comment] 2021-05-25 15:46
> also animepahe doesnt seem to be working even though its mentioned it works in the documentation
> also how to do a re-search as sometimes all the results dont show
> the one im searching for is nanatsu no taizai fundo no shinpan
> ![image](https://user-images.githubusercontent.com/83282129/119445401-d0488380-bd3d-11eb-8896-13f001631279.png)

AnimePahe will start to work again once https://github.com/anime-dl/anime-downloader/pull/674 gets merged.

**Comment by ArjixWasTaken** [comment] 2021-05-25 15:50
You can install that fork for now if you desperately want animepahe.
To do so download https://github.com/nate-moo/anime-downloader/archive/refs/heads/KwikFix.zip
Then install it in the same way you installed anime-dl (previously).

animepahe should be working after that
oh yeah, even if it is going to work, it will only download m3u8 (playlist files) not mp4, so its only good for streaming for now

**Comment by thaynos** [comment] 2021-05-25 16:34
> You can install that fork for now if you desperately want animepahe.
> To do so download https://github.com/nate-moo/anime-downloader/archive/refs/heads/KwikFix.zip
> Then install it in the same way you installed anime-dl (previously).
> 
> animepahe should be working after that
> oh yeah, even if it is going to work, it will only download m3u8 (playlist files) not mp4, so its only good for streaming for now

will there ever be downloads supported for animepahe
many scripts ive used dont work anymore for animepahe
ig its bcz of the added captcha
ive tried using monkey-dl but it requires 2captcha which is paid which kinda beats the purpose even if its a few cents

**Comment by AbdullahM0hamed** [comment] 2021-05-26 19:08
Closing as the original issue appears to be resolved.

**Closed by AbdullahM0hamed** 2021-05-26 19:08 UTC
